language: csharp
solution: FuelPrice.sln
mono: none
dotnet: 2.1.302
install:
  - dotnet tool install --global dotnet-sonarscanner
script:
  - dotnet build ./Activout.FuelPrice/
#  - dotnet test ./Activout.FuelPrice.Test/
  - $HOME/.dotnet/tools/dotnet-sonarscanner begin /k:"Activout.FuelPrice" /d:sonar.organization="activout" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /version:"$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT"
  - dotnet build
  - $HOME/.dotnet/tools/dotnet-sonarscanner end /d:sonar.login="$SONAR_TOKEN"
cache:
  directories:
    - $HOME/.nuget
    - $HOME/.sonar/cache
